obstacle_range: 4.0
raytrace_range: 5.0
#robot_radius: 0.20 
footprint: [[0.17,-0.19],[-0.33,-0.1],[-0.33,0.1],[0.17,0.19]]
inflation_radius: 0.10
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}


